### PR TITLE
Add support for Timezones

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
@dotnet/aspnet-build could I get help with this error:

```
.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.20113.5\tools\Sign.proj(81,5): error SIGN001: Signing 3rd party library 'D:\a\1\s\artifacts\tmp\Release\ContainerSigning\32\tools/dotnetwasm/framework/System.Net.Http.WebAssemblyHttpHandler.dll' with Microsoft certificate 'Microsoft400'. The library is considered 3rd party library due to its copyright: ''.
```

How do I resolve this?

**Comment by dougbu** [comment]
Sorry, @pranavkm I only have debugging suggestions such as packing the project locally or examining the bin log of the failing build.

In general `$(DisableArcadeProjectLayout)` from the Directory.Build.props file could be doing all kind of weird things, breaking unintended parts of Arcade. But I don't see how the small change in the failing project relates.

**Comment by captainsafia** [comment]
When I tried this script locally, I got the following warnings in the `zic` command invocation. is this expected?

````
"obj/data/input/asia", line 2252: warning: time zone abbreviation differs from POSIX standard (+06)
"obj/data/input/asia", line 2262: warning: time zone abbreviation differs from POSIX standard (+04)
"obj/data/input/asia", line 2263: warning: time zone abbreviation differs from POSIX standard (+05)
"obj/data/input/asia", line 2264: warning: time zone abbreviation differs from POSIX standard (+06)
"obj/data/input/asia", line 2273: warning: time zone abbreviation differs from POSIX standard (+03)
"obj/data/input/asia", line 2274: warning: time zone abbreviation differs from POSIX standard (+05)
```

**Comment by pranavkm** [comment]
Thanks @dougbu, I was able to figure out what was wrong (I had to turn off signing for a renamed filed).

@captainsafia  I did not see this locally. There's a reference to the warning here: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8151876 which says this could be safely ignored. I wonder if it's caused by a difference in the version.

**Comment by pranavkm** [comment]
I'm going to get this PR but leave it open to get some head start on change in AspNetCore.

**Pull request merged**
